displayName=Nex Splits
author=zneix
support=https://github.com/zneix/nex-splits
description=Detailed time tracking for Nex
tags=nex, godwars, dungeon, gwd, splits,torva,zaros,ancient,time,timer
plugins=com.nexsplits.NexSplitsPlugin
